name: Deploy Resume (Docker + Traefik)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy resume to OCI VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
             set -e
                    
             # Clone/update repo in a SAFE location
             cd /var/www/repo
                    
             if [ ! -d html ]; then
               git clone https://github.com/Sairaj567/html.git
             else
               cd html && git pull origin master
               cd ..
             fi
                    
             # Deploy site files to web root
             rsync -av --delete /var/www/repo/html/html/ /var/www/html/
                    
